name: pandas_workshop
channels: 
    - conda-forge
dependencies: 
    - python>=3.8.0,<=3.11.10
    - jupyterlab=3.5.2
    - matplotlib=3.6.3
    - numpy=1.24.1
    - pandas=1.5.3
    - requests=2.28.2
    - seaborn=0.12.2
